ENCODER_MAP_ENABLE = yes

ifeq ($(strip $(RGB_MATRIX_ENABLE)), yes)
    OPT_DEFS += -DCAPS_LOCK_INDICATOR_ENABLE
    OPT_DEFS += -DCAPS_LOCK_INDICATOR_LIGHT_ALPHAS
    OPT_DEFS += -DFN_LAYER_TRANSPARENT_KEYS_OFF

    SRC += rgb_matrix_user.c
endif
